kind: pipeline
name: python-latest

workspace:
  base: /app
  path: .

steps:
  - name: test
    image: python:3
    commands:
      - make test-env test
  - name: push to pypi
    image: python:3
    commands:
      - make build-env upload
    secrets:
      - source: PYPI_USERNAME
        target: TWINE_USERNAME
      - source: PYPI_PASSWORD
        target: TWINE_PASSWORD
    when:
      event: [ tag ]
  - name: notify
    image: drillster/drone-email
    host: $SMTP_HOST
    username: $SMTP_USER
    password: $SMTP_PASS
    from: drone@iamthefij.com
    when:
      status: [ changed, failure ]

---
kind: pipeline
name: python-3.6

workspace:
  base: /app
  path: .


steps:
  - name: test
    image: python:3.6
    commands:
      - make test-env test

---
kind: pipeline
name: python-3.7

workspace:
  base: /app
  path: .


steps:
  - name: test
    image: python:3.7
    commands:
      - make test-env test
