kind: pipeline
name: python-latest

workspace:
  base: /app
  path: .

steps:
  - name: test
    image: python:3
    commands:
      - make test-env test
  - name: push to pypi
    image: python:3
    commands:
      - make build-env upload
    environment:
      TWINE_USERNAME:
        from_secret: PYPI_USERNAME
      TWINE_PASSWORD:
        from_secret: PYPI_PASSWORD
    when:
      event: [ tag ]
  - name: notify
    image: drillster/drone-email
    settings:
      host:
        from_secret: SMTP_HOST
      username:
        from_secret: SMTP_USER
      password:
        from_secret: SMTP_PASS
      from: drone@iamthefij.com
    when:
      status: [ changed, failure ]

---
kind: pipeline
name: python-3.6

workspace:
  base: /app
  path: .


steps:
  - name: test
    image: python:3.6
    commands:
      - make test-env test

---
kind: pipeline
name: python-3.7

workspace:
  base: /app
  path: .


steps:
  - name: test
    image: python:3.7
    commands:
      - make test-env test
