workspace:
  base: /app
  path: .

pipeline:
  test:
    image: python:3
    commands:
      - make test-env test
  push_to_pypi:
    image: python:3
    commands:
      - make build-env upload
    secrets:
      - source: PYPI_USERNAME
        target: TWINE_USERNAME
      - source: PYPI_PASSWORD
        target: TWINE_PASSWORD
    when:
      event: tag
      branch: master
