workspace:
  base: /app
  path: .

pipeline:
  test:
    image: python:3
    commands:
      - python3 -m venv env
      - ./env/bin/pip install tox
      - make test
  push_to_pypi:
    image: python:3
    commands:
      - ./env/bin/pip install twine
      - make upload-test
    secrets:
      - source: PYPI_USERNAME
        target: TWINE_USERNAME
      - source: PYPI_PASSWORD
        target: TWINE_PASSWORD
    when:
      event: tag
      branch: master
