language: generic
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python3.4 python3-pip python3.4-venv
install:
  - python3 -m venv env
  # travis had an issue...
  - ./env/bin/pip install -U setuptools
  - make test-env
script:
  - make test
